CC?=gcc
#CFLAGS+=`pkg-config --cflags sdl2`
CFLAGS+=-ISDL
LIBS+=`pkg-config --libs sdl2`

all: clean \
	dat2inc \
	datafile

datafile:
	$(CC) $(CFLAGS) $(LIBS) -o datafile datafile.c bme_end.c
	strip datafile

dat2inc:
	$(CC) $(CFLAGS) $(LIBS) -o dat2inc dat2inc.c
	strip dat2inc

clean:
	$(RM) *.o
	$(RM) datafile
	$(RM) dat2inc
