CC?=gcc
CFLAGS+=-ISDL
LIBS+=$(pkg-config --cflags --libs sdl2)

all: clean dat2inc.exe datafile.exe

datafile.exe:
	$(CC) $(CFLAGS) $(LIBS)  -o datafile.exe datafile.c bme_end.c
	strip datafile.exe

dat2inc.exe:
	$(CC) $(CFLAGS) $(LIBS)  -o dat2inc.exe dat2inc.c
	strip dat2inc.exe

clean:
	$(RM) *.o
	$(RM) datafile.exe
	$(RM) dat2inc.exe
