CC?=gcc
CFLAGS+=`pkg-config --cflags sdl2`
LIBS+=`pkg-config --libs sdl2`


all: dat2inc datafile

datafile: datafile.c bme_end.c
	$(CC) $(CFLAGS) -o datafile datafile.c bme_end.c
	strip datafile

dat2inc: dat2inc.c
	$(CC) $(LIBS) -o dat2inc dat2inc.c
	strip dat2inc
